@host = put.your.host.here

### Upload png
# @name upload_response
POST {{host}}/images HTTP/1.1
Content-Type: application/json

{"blob": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAolBMVEW+YvTAZe/DaeflqHz3yUL4y0DCaOrjpoDdmZXcl5n3yEThooa/Y/L2x0XfnY/gnoz1xUi+Y/PstWXShrXYkaL5zD3BZ+zlqXruuF/mqXnBZuzEbeHIc9XgoIr61mX++uv5zUH61mTIdNXJdtLhoYj723X////5zkXJdtHGcdr5zkP601b60lT5zUDDbOS/ZPDShbfzwVH3yUPYkaTrtGfNfMcjNT0+AAAAAWJLR0QmWgiYtQAAAAlwSFlzAAAA4wAAAOMBD+bfpwAAAAd0SU1FB+QGHBMnLCLzLRwAAACDSURBVBjTY2DAARgZUbhMzCyszGxIAuwsHJxc3Ag+Dy8fAwO/gCDCACFhBgYRUTEYX4xZHAgkRCWloALSolAgDeHLyIrKySsoyCuKyiqBBZRVRFXV1NXVVEVVNCBKNEW1tEVFdXRFNaFm6MHM0IMK6BsYGhkbAIE+3CEmpmhe02fADQCAdAqOlVBsrAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wNi0yOFQxOTozOTo0NCswMjowMJMOJl4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDYtMjhUMTk6Mzk6NDQrMDI6MDDiU57iAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAFd6VFh0UmF3IHByb2ZpbGUgdHlwZSBpcHRjAAB4nOPyDAhxVigoyk/LzEnlUgADIwsuYwsTIxNLkxQDEyBEgDTDZAMjs1Qgy9jUyMTMxBzEB8uASKBKLgDqFxF08kI1lQAAAABJRU5ErkJggg=="}

### Get png
@id = {{upload_response.response.body.id}}
GET {{host}}/images/{{id}}.png HTTP/1.1

### Get jpg
GET {{host}}/images/{{id}}.jpg HTTP/1.1